project_id = "vgvvwcswjwqfdxjfidws"

[functions.analyze-food]
verify_jwt = false

[functions.generate-health-plan]
verify_jwt = false

[functions.generate-grocery-list]
verify_jwt = false

[functions.suggest-meal-swap]
verify_jwt = false
